Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/07/2024
Var
// Seção de Declarações das variáveis 
INDICE, SOMA, K: inteiro

Inicio
INDICE <- 6
SOMA <- 0
K <- 0
Enquanto (K < INDICE) faca
  K <- K + 1
  SOMA <- SOMA + K
  escreval(K)
FimEnquanto

Escreval("O resultado final é:",SOMA)

Fimalgoritmo