Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/07/2024
Var
// Seção de Declarações das variáveis 
 X,Y,Z, I: inteiro

Inicio

X <- 3
Y <- 4
Z <- 5

se ((X - 1) > 2) entao
Y <- Y + 1
senao
  Y <- Y - 1
fimse
Z <- X + Y

para I de 1 ate 8 faca
  Y <- Y + 1
fimpara

Z <- Z + Y
escreva(z)


Fimalgoritmo